FROM alpine:3.6
## Its to generate root directory ##
RUN cd /root && touch ".builded.$(date +%F_%R)" && cd / && \
    apk --update add --no-cache \
        nodejs nodejs-npm
COPY package.json /app/package.json
WORKDIR /app
RUN set -x && \
	npm install --production && \
    npm cache clean
COPY ./public /app/public
COPY ./server /app/server
EXPOSE 8080
CMD ["npm", "run", "start"]